
# Set up global varible to track recent touch
globals:
  - id: recent_touch
    type: bool
    restore_value: no
    initial_value: "true"

# Setup LED and Backlight
light:
  - platform: monochromatic
    output: backlight_pwm
    name: Display Backlight
    id: backlight
    restore_mode: ALWAYS_ON
  - platform: rgb
    name: LED
    id: led
    red: output_red
    green: output_green
    blue: output_blue
    restore_mode: ALWAYS_OFF

# Set UART pins
uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600

# Set placeholder sensor for tracking powerstate
binary_sensor:

  - platform: template
    name: powerstate
    id: powerstate
    publish_initial_state: true


# Hardware related setup
spi:
  - id: tft
    clk_pin: GPIO14
    mosi_pin: GPIO13
    miso_pin: GPIO12
  - id: touch
    clk_pin: GPIO25
    mosi_pin: GPIO32
    miso_pin: GPIO39

output:
  - platform: ledc
    pin: GPIO21
    id: backlight_pwm
  - platform: ledc
    id: output_red
    pin: GPIO4
    inverted: true
  - platform: ledc
    id: output_green
    pin: GPIO16
    inverted: true
  - platform: ledc
    id: output_blue
    pin: GPIO17
    inverted: true

interval:
    # Every 30 seconds check for recent touch
    # dim the backlight to 50% if not
  - interval: 30s
    then:
      - if:
          condition:
            lambda: |-
                return !id(recent_touch);
          then: 
            - light.control:
                id: backlight
                brightness: 50%
          else:
            - lambda: |-
                id(recent_touch) = false;

# Display setup
display:
  - platform: ili9xxx
    id: my_display
    model: ili9341
    spi_id: tft
    cs_pin: GPIO15
    dc_pin: GPIO2
    invert_colors: false
    transform:
      swap_xy: true
    dimensions:
      width: 320
      height: 240
    auto_clear_enabled: False
    update_interval: never
    data_rate: 40MHz

# Touchscreen setup
touchscreen:
  id: my_touch
  platform: xpt2046
  spi_id: touch
  cs_pin: GPIO33
  interrupt_pin: GPIO36
  update_interval: 50ms
  threshold: 600
  calibration:
    x_min: 180
    x_max: 3800
    y_min: 240
    y_max: 3860
  transform:
    swap_xy: true